"""create user model

Revision ID: 4bf4c69d8fe8
Revises: 598f2a4c0333
Create Date: 2024-09-23 17:17:54.314674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf4c69d8fe8'
down_revision = '598f2a4c0333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('img_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('img_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('user')
    # ### end Alembic commands ###
