"""add img_name

Revision ID: 598f2a4c0333
Revises: 
Create Date: 2024-09-19 23:50:15.484008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598f2a4c0333'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###
